### PR TITLE
Speedup

### PR DESCRIPTION
**Pull request by banduri**
did some speedups for classification. Mainly use a pre initializied array for ipaddress or networkaddresses if possible. also i could not not get jruby + logstash-devutils to work on my system so i did not execute the tests i added. But it should work since the benchmark provided the expected results for classification.

### CODE REVIEW

**Comment by purbon** [comment]
Hi @banduri, thanks a lot for your benchmark. I would more than happy review and merge your improvements. 

The first thing i noticed is about the benchmark results, not sure there is the best place to place them. I would say keeping them out of the project as they are is the best thing. What you can for example is adding some documentation to explain how fast/slow this plugin is, do you agree? something like a `docs/performance.md`  document where you explain your results and methodology. But I would keep the raw results out of the project as they are now because people need some context to understand them :smile_cat: 

Looking forward to test this more!
- purbon

**Comment by banduri** [comment]
Same here not sure about putting the benchmark results at all. Better names for the four new parameters and a proper documentation of them would also do the job. But yes, I do agree `docs/performace.md` is a better place (moving)

**Comment by purbon** [comment]
Thanks for the work @banduri, this is really good. In order to move forward with your PR is going to be necessary to sign the CLA agreement, you can find more information at https://www.elastic.co/contributor-agreement.

**Comment by purbon** [comment]
I would also suggest to squash the PR before getting this in :+1:, then we would have a cleaner history in git. What do you think?

**Comment by banduri** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hi Pere

On 09/04/2015 03:09 PM, Pere Urbón wrote:

> I would also suggest to squash the PR before getting this in :+1:,
> then we would have a cleaner history in git. What do you think?

I'm not sure how to sign a CLA. I wasn't aware that providing some
code licensed under the Apache License version 2.0 could lead to
problems but I do understand the need for a CLA and totaly agree with
it. That said, I think subscribing to a newsletter is hard to compare
with signing a CLA.

But sure. I can squash it ... rewriting history ;)

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJV6e1NAAoJEFvGnxXo8wMhUAoQAJLTpg4p7gn9Gy5AyDJu1D9p
CP/xg57r6BY2vMSEzYvjIDARqD9h8S+uK4nZWK2bMHnWRt6H+4Xfw9HAYYxXPBhd
gSquz6IrdH+ca8xn9w4MMog4uwrreoReUQkoTgnQXL5RcDdYCtkpGIE3mcvg+u1v
/zgRqmZDGm2mYm60dkbOum2YOEdB4R5YgeSQIAfjKWKPVJ3UYztxr9OfpTwgPuIU
8YcwHTG6xoAV7wvEAiP2bVGEVfwTUHoemZusiOyciUKdTIYJq16MXnKUj/k9Yq9W
FpQyuYlo+yYlaxG8kU6WBmhd3mm7aV4b2RNvCzy+n8C+GN+ImV6KeK9WfNyrRP7a
NhJ0tjiEYwjhdkx3RR/HrN8hTnQHhqXw5PCn7sf0CqjasY9LLr2MrVT8/4thijtR
11in5/dir/GzHzVR/SCKHFWIn8slAsXe3sYNWlJXzc7DQVIFmTKP5fVdFyOrcixR
Y4Aj2U4FsRX2NP/yPHJjLXpEDMOiYSoIzerJ3z9kwilPO756mdjfJju1UfeS+fEt
Wq23pNGBAc22DcflAJahZ81GfEL3OMMZYktPpojCQPZML8i3qvfChG4Gm4Of3vsL
5TaY7MsiUPM99r2d5uv6vGP33ft3+8L3FCaKmqsc3d9JBUE459UCEsTqokEv/bMw
z2vhIuFJ6n/CxqMiGv15
=JyH8
-----END PGP SIGNATURE-----

**Comment by purbon** [comment]
@banduri thanks for your understanding, I'm an engineer so all this CLA and license things are mostly out of my complete understanding.  Let me know when the CLA is signed so I can get this in :P thanks a lot!

On the other side, I don't understand the newsletter comparison? is this something I said? 
- purbon

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by purbon** [comment]
Closing this for now as the long standing CLA signature request not fulfilled, more than welcome to reopen and merge if the CLA gets signed. In the meanwhile I opened https://github.com/logstash-plugins/logstash-filter-cidr/issues/3 to keep track of the improvements.

**Pull request closed without merging**
